db:
  port: 5433
  sslmode: disable
  host: localhost
  username: postgres
  dbname: postgres

http:
  port: 80
  MaxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  port: 50080

grpcRA:
  port: 58080
  host: localhost

grpcCS:
  port: 8091
  host: localhost

grpsPS:
  port: 58082
  host: localhost


